version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows

archives:
  - format: tar.gz
    # This name template makes the OS and Arch names user-friendly.
    name_template: >-
      {{ .ProjectName }}_{{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Include the entire bin folder (with arch specific subfolders)
    files:
      - "bin/{{ .Arch }}/{{ .OS }}/**"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    ---
    [c] 2025 Cinea